name: danielgarcia
favicon: null
layout_spectrum: 0.15895
typography_spectrum: 0.57551
title: Vendus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#63665d'
    - '#9bbc2c'
    - '#ffffff'
    - '#bed46f'
    - '#83837c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.9926920558791608
  rhythmicContrast: 0.75
purpose: []
